.PHONY: venv
venv:
	conda create --name {{project_name}} python={{python_version}} -y
	conda activate {{project_name}}
	python3 -m pip install -r requirements.txt
	python3 -m pip install -r requirements-dev.txt
	python3 -m pip install -r requirements-test.txt

.PHONY: api-run
api-run:
	uvicorn app.main:app --reload --workers 1 --host 0.0.0.0
