---
name: CI-CD
on: [push, pull_request]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.8']

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4.3.1
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: x64

            - name: Check where we are
              run: |
                  pwd
                  cd ..
                  python -m pip install copier
                  copier api-template . --defaults
                  cd test-project-api
                  pwd

            - name: Install Python dependencies
              run: |
                  cd ..
                  cd test-project-api
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
                  python -m pip install -r requirements-test.txt

            - name: Run test suite
              run: |
                  cd ..
                  cd test-project-api
                  python -m pytest -v --cov

            # - name: Upload coverage to Codecov
            #   uses: codecov/codecov-action@v3
