---
name: CI-CD
on: [push, pull_request]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.8']

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4.2.0
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: x64

            - name: Check where we are.
              run: |
                  pwd
                  cd ..
                  cd test-project-api
                  pwd

            # - name: Install Python dependencies
            #   run: |
            #       python -m pip install --upgrade pip
            #       python -m pip install -r requirements.txt
            #       python -m pip install -r requirements-test.txt

            # - name: Run test suite
            #   run: python -m pytest -v --cov

            # - name: Upload coverage to Codecov
            #   uses: codecov/codecov-action@v3
